[versions]
android = "8.13.2"
androidX-activity = "1.11.0"
androidX-lifecycle = "2.9.4"
atomic = "0.32.1"
buildConfig = "6.0.9"
coroutines = "1.11.0"
dokka = "2.2.0"
kotlin = "2.3.21"
kotlinPoet = "2.3.0"
kotlinSerialization = "1.11.0"
shadow = "9.4.1"
sonatypeMavenCentral = "2.1.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android" }
g000sha256-sonatypeMavenCentral = { id = "dev.g000sha256.sonatype-maven-central", version.ref = "sonatypeMavenCentral" }
gmazzo-buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
gradle-application = { id = "application" }
gradleup-shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jetBrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
jetBrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetBrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetBrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[libraries]
libraries-androidX-activity = { module = "androidx.activity:activity", version.ref = "androidX-activity" }
libraries-androidX-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidX-lifecycle" }
libraries-androidX-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidX-lifecycle" }
libraries-jetBrains-atomic = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomic" }
libraries-jetBrains-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
libraries-jetBrains-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
libraries-jetBrains-kotlinSerialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinSerialization" }
libraries-jetBrains-kotlinSerialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
libraries-squareUp-kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
