/*
 * Copyright 2025 Georgii Ippolitov (g000sha256)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.g000sha256.tdl.dto

import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String

/**
 * A stake dice message. The dice value is randomly generated by the server.
 *
 * @property initialState The animated stickers with the initial dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known.
 * @property finalState The animated stickers with the final dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known.
 * @property value The dice value. If the value is 0, then the dice don't have final state yet.
 * @property stakeToncoinAmount The amount of Toncoins that were staked; in the smallest units of the currency.
 * @property prizeToncoinAmount The amount of Toncoins that were gained from the roll; in the smallest units of the currency; -1 if the dice don't have final state yet.
 */
public class MessageStakeDice public constructor(
    public val initialState: DiceStickers?,
    public val finalState: DiceStickers?,
    public val value: Int,
    public val stakeToncoinAmount: Long,
    public val prizeToncoinAmount: Long,
) : MessageContent() {
    override fun equals(other: Any?): Boolean {
        if (other === this) {
            return true
        }
        if (other == null) {
            return false
        }
        if (other::class != this::class) {
            return false
        }
        other as MessageStakeDice
        if (other.initialState != initialState) {
            return false
        }
        if (other.finalState != finalState) {
            return false
        }
        if (other.value != value) {
            return false
        }
        if (other.stakeToncoinAmount != stakeToncoinAmount) {
            return false
        }
        return other.prizeToncoinAmount == prizeToncoinAmount
    }

    override fun hashCode(): Int {
        var hashCode = this::class.hashCode()
        hashCode = 31 * hashCode + initialState.hashCode()
        hashCode = 31 * hashCode + finalState.hashCode()
        hashCode = 31 * hashCode + value.hashCode()
        hashCode = 31 * hashCode + stakeToncoinAmount.hashCode()
        hashCode = 31 * hashCode + prizeToncoinAmount.hashCode()
        return hashCode
    }

    override fun toString(): String {
        return buildString {
            append("MessageStakeDice")
            append("(")
            append("initialState=")
            append(initialState)
            append(", ")
            append("finalState=")
            append(finalState)
            append(", ")
            append("value=")
            append(value)
            append(", ")
            append("stakeToncoinAmount=")
            append(stakeToncoinAmount)
            append(", ")
            append("prizeToncoinAmount=")
            append(prizeToncoinAmount)
            append(")")
        }
    }
}
