/*
 * Copyright 2025 Georgii Ippolitov (g000sha256)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.g000sha256.tdl.dto

import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String

/**
 * A dice message. The dice value is randomly generated by the server.
 *
 * @property initialState The animated stickers with the initial dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known.
 * @property finalState The animated stickers with the final dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known.
 * @property emoji Emoji on which the dice throw animation is based.
 * @property value The dice value. If the value is 0, the dice don't have final state yet.
 * @property successAnimationFrameNumber Number of frame after which a success animation like a shower of confetti needs to be shown on updateMessageSendSucceeded.
 */
public class MessageDice public constructor(
    public val initialState: DiceStickers?,
    public val finalState: DiceStickers?,
    public val emoji: String,
    public val value: Int,
    public val successAnimationFrameNumber: Int,
) : MessageContent() {
    override fun equals(other: Any?): Boolean {
        if (other === this) {
            return true
        }
        if (other == null) {
            return false
        }
        if (other::class != this::class) {
            return false
        }
        other as MessageDice
        if (other.initialState != initialState) {
            return false
        }
        if (other.finalState != finalState) {
            return false
        }
        if (other.emoji != emoji) {
            return false
        }
        if (other.value != value) {
            return false
        }
        return other.successAnimationFrameNumber == successAnimationFrameNumber
    }

    override fun hashCode(): Int {
        var hashCode = this::class.hashCode()
        hashCode = 31 * hashCode + initialState.hashCode()
        hashCode = 31 * hashCode + finalState.hashCode()
        hashCode = 31 * hashCode + emoji.hashCode()
        hashCode = 31 * hashCode + value.hashCode()
        hashCode = 31 * hashCode + successAnimationFrameNumber.hashCode()
        return hashCode
    }

    override fun toString(): String {
        return buildString {
            append("MessageDice")
            append("(")
            append("initialState=")
            append(initialState)
            append(", ")
            append("finalState=")
            append(finalState)
            append(", ")
            append("emoji=")
            append(emoji)
            append(", ")
            append("value=")
            append(value)
            append(", ")
            append("successAnimationFrameNumber=")
            append(successAnimationFrameNumber)
            append(")")
        }
    }
}
