name: Update TDLib

on:
  push:
    branches:
      - update-td

jobs:
  build-android:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Setup dependencies
        run: sudo apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake g++

      - name: Check environment
        run: |
          cd td/example/android
          ./check-environment.sh

      - name: Fetch Android SDK
        run: |
          cd td/example/android
          ./fetch-sdk.sh

      - name: Build OpenSSL
        run: |
          cd td/example/android
          ./build-openssl.sh

      - name: Build TDLib
        run: |
          cd td/example/android
          ./build-tdlib.sh '' '' '' '' 'JSON'

      - name: Show files
        run: find td/example/android/tdlib -name '*.so' -type f

      - name: SHA256 checksums
        run: |
          shasum -a 256 td/example/android/tdlib/libs/arm64-v8a/libtdjson.so
          shasum -a 256 td/example/android/tdlib/libs/armeabi-v7a/libtdjson.so
          shasum -a 256 td/example/android/tdlib/libs/x86/libtdjson.so
          shasum -a 256 td/example/android/tdlib/libs/x86_64/libtdjson.so

      - name: Copy libs
        run: |
          rm -r tdl-coroutines/src/androidMainGenerated/jniLibs/{arm64-v8a,armeabi-v7a,x86,x86_64}
          mkdir tdl-coroutines/src/androidMainGenerated/jniLibs/{arm64-v8a,armeabi-v7a,x86,x86_64}
          cp td/example/android/tdlib/libs/arm64-v8a/libtdjson.so tdl-coroutines/src/androidMainGenerated/jniLibs/arm64-v8a/libtdjson.so
          cp td/example/android/tdlib/libs/armeabi-v7a/libtdjson.so tdl-coroutines/src/androidMainGenerated/jniLibs/armeabi-v7a/libtdjson.so
          cp td/example/android/tdlib/libs/x86/libtdjson.so tdl-coroutines/src/androidMainGenerated/jniLibs/x86/libtdjson.so
          cp td/example/android/tdlib/libs/x86_64/libtdjson.so tdl-coroutines/src/androidMainGenerated/jniLibs/x86_64/libtdjson.so

      - name: Commit and push libs
        uses: EndBug/add-and-commit@v9
        with:
          pull: --rebase --autostash
          author_name: Georgii Ippolitov
          author_email: detmmpmznb@g000sha256.dev
          committer_name: GitHub
          committer_email: noreply@github.com
          message: TDLib for Android [skip ci]
          add: tdl-coroutines

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.1
          cache-disabled: false

      - name: Assemble generator
        run: ./gradlew tdl-coroutines-generator:assemble

      - name: Run generator
        run: ./gradlew tdl-coroutines-generator:run

      - name: Commit and push code changes
        uses: EndBug/add-and-commit@v9
        with:
          pull: --rebase --autostash
          author_name: Georgii Ippolitov
          author_email: detmmpmznb@g000sha256.dev
          committer_name: GitHub
          committer_email: noreply@github.com
          message: Update API [skip ci]
          add: |
            - tdl-coroutines
            - README.md

  build-jvm-linux-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Setup dependencies
        run: sudo apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake g++

      - name: Build TDLib
        run: |
          cd td
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON -DTD_JSON_JAVA=ON ..
          cmake --build . --target install
          cd ../example/java
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DTd_DIR:PATH=$(readlink -e ../td/lib/cmake/Td) ..
          cmake --build . --target install

      - name: Show files
        run: find td/tdlib/bin -name '*.so' -type f

      - name: SHA256 checksum
        run: shasum -a 256 td/tdlib/bin/libtdjni.so

      - name: Copy lib
        run: |
          rm -r tdl-coroutines/src/jvmMainGenerated/resources/libs/linux-arm64
          mkdir tdl-coroutines/src/jvmMainGenerated/resources/libs/linux-arm64
          cp td/tdlib/bin/libtdjni.so tdl-coroutines/src/jvmMainGenerated/resources/libs/linux-arm64/libtdjni.so

      - name: Commit and push lib
        uses: EndBug/add-and-commit@v9
        with:
          pull: --rebase --autostash
          author_name: Georgii Ippolitov
          author_email: detmmpmznb@g000sha256.dev
          committer_name: GitHub
          committer_email: noreply@github.com
          message: TDLib for JVM Linux Arm64 [skip ci]
          add: tdl-coroutines

  build-jvm-linux-x64:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Setup dependencies
        run: sudo apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake g++

      - name: Build TDLib
        run: |
          cd td
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON -DTD_JSON_JAVA=ON ..
          cmake --build . --target install
          cd ../example/java
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DTd_DIR:PATH=$(readlink -e ../td/lib/cmake/Td) ..
          cmake --build . --target install

      - name: Show files
        run: find td/tdlib/bin -name '*.so' -type f

      - name: SHA256 checksum
        run: shasum -a 256 td/tdlib/bin/libtdjni.so

      - name: Copy lib
        run: |
          rm -r tdl-coroutines/src/jvmMainGenerated/resources/libs/linux-x64
          mkdir tdl-coroutines/src/jvmMainGenerated/resources/libs/linux-x64
          cp td/tdlib/bin/libtdjni.so tdl-coroutines/src/jvmMainGenerated/resources/libs/linux-x64/libtdjni.so

      - name: Commit and push lib
        uses: EndBug/add-and-commit@v9
        with:
          pull: --rebase --autostash
          author_name: Georgii Ippolitov
          author_email: detmmpmznb@g000sha256.dev
          committer_name: GitHub
          committer_email: noreply@github.com
          message: TDLib for JVM Linux x64 [skip ci]
          add: tdl-coroutines

  build-jvm-macos-arm64:
    runs-on: macos-15
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Setup dependencies
        run: brew install gperf cmake openssl coreutils

      - name: Build TDLib
        run: |
          cd td
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DJAVA_HOME=/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/ -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl/ -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON -DTD_JSON_JAVA=ON ..
          cmake --build . --target install
          cd ../example/java
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DJAVA_HOME=/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/ -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DTd_DIR:PATH=$(greadlink -e ../td/lib/cmake/Td) ..
          cmake --build . --target install

      - name: Show files
        run: find td/tdlib/bin -name '*.dylib' -type f

      - name: SHA256 checksum
        run: shasum -a 256 td/tdlib/bin/libtdjni.dylib

      - name: Copy lib
        run: |
          rm -r tdl-coroutines/src/jvmMainGenerated/resources/libs/macos-arm64
          mkdir tdl-coroutines/src/jvmMainGenerated/resources/libs/macos-arm64
          cp td/tdlib/bin/libtdjni.dylib tdl-coroutines/src/jvmMainGenerated/resources/libs/macos-arm64/libtdjni.dylib

      - name: Commit and push lib
        uses: EndBug/add-and-commit@v9
        with:
          pull: --rebase --autostash
          author_name: Georgii Ippolitov
          author_email: detmmpmznb@g000sha256.dev
          committer_name: GitHub
          committer_email: noreply@github.com
          message: TDLib for JVM macOS Arm64 [skip ci]
          add: tdl-coroutines

  build-jvm-macos-x64:
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Setup dependencies
        run: brew install gperf cmake openssl coreutils

      - name: Build TDLib
        run: |
          cd td
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DJAVA_HOME=/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/ -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl/ -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON -DTD_JSON_JAVA=ON ..
          cmake --build . --target install
          cd ../example/java
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DJAVA_HOME=/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/ -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DTd_DIR:PATH=$(greadlink -e ../td/lib/cmake/Td) ..
          cmake --build . --target install

      - name: Show files
        run: find td/tdlib/bin -name '*.dylib' -type f

      - name: SHA256 checksum
        run: shasum -a 256 td/tdlib/bin/libtdjni.dylib

      - name: Copy lib
        run: |
          rm -r tdl-coroutines/src/jvmMainGenerated/resources/libs/macos-x64
          mkdir tdl-coroutines/src/jvmMainGenerated/resources/libs/macos-x64
          cp td/tdlib/bin/libtdjni.dylib tdl-coroutines/src/jvmMainGenerated/resources/libs/macos-x64/libtdjni.dylib

      - name: Commit and push lib
        uses: EndBug/add-and-commit@v9
        with:
          pull: --rebase --autostash
          author_name: Georgii Ippolitov
          author_email: detmmpmznb@g000sha256.dev
          committer_name: GitHub
          committer_email: noreply@github.com
          message: TDLib for JVM macOS x64 [skip ci]
          add: tdl-coroutines

  build-jvm-windows-arm64:
    runs-on: windows-11-arm
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Setup dependencies
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg.exe install gperf:arm64-windows openssl:arm64-windows zlib:arm64-windows

      - name: Build TDLib
        run: |
          cd td
          mkdir build
          cd build
          cmake -A ARM64 -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON -DTD_JSON_JAVA=ON -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build . --target install --config Release
          cd ../example/java
          mkdir build
          cd build
          cmake -A ARM64 -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../../../vcpkg/scripts/buildsystems/vcpkg.cmake -DTd_DIR:PATH=$(Resolve-Path ../td/lib/cmake/Td) ..
          cmake --build . --target install --config Release

      - name: Show files
        run: Get-ChildItem -Filter *.dll -Recurse

      - name: SHA256 checksums
        run: |
          Get-FileHash td/tdlib/bin/libcrypto-3-arm64.dll -Algorithm SHA256
          Get-FileHash td/tdlib/bin/libssl-3-arm64.dll -Algorithm SHA256
          Get-FileHash td/tdlib/bin/tdjni.dll -Algorithm SHA256
          Get-FileHash td/tdlib/bin/zlib1.dll -Algorithm SHA256

      - name: Copy libs
        run: |
          Remove-Item -Recurse tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-arm64
          New-Item -ItemType Directory -Path tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-arm64
          Copy-Item td/tdlib/bin/libcrypto-3-arm64.dll -Destination tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-arm64/libcrypto-3-arm64.dll
          Copy-Item td/tdlib/bin/libssl-3-arm64.dll -Destination tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-arm64/libssl-3-arm64.dll
          Copy-Item td/tdlib/bin/tdjni.dll -Destination tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-arm64/tdjni.dll
          Copy-Item td/tdlib/bin/zlib1.dll -Destination tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-arm64/zlib1.dll

      - name: Commit and push libs
        uses: EndBug/add-and-commit@v9
        with:
          pull: --rebase --autostash
          author_name: Georgii Ippolitov
          author_email: detmmpmznb@g000sha256.dev
          committer_name: GitHub
          committer_email: noreply@github.com
          message: TDLib for JVM Windows Arm64 [skip ci]
          add: tdl-coroutines

  build-jvm-windows-x64:
    runs-on: windows-2025
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Setup dependencies
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows

      - name: Build TDLib
        run: |
          cd td
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON -DTD_JSON_JAVA=ON -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build . --target install --config Release
          cd ../example/java
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../../../vcpkg/scripts/buildsystems/vcpkg.cmake -DTd_DIR:PATH=$(Resolve-Path ../td/lib/cmake/Td) ..
          cmake --build . --target install --config Release

      - name: Show files
        run: Get-ChildItem -Filter *.dll -Recurse

      - name: SHA256 checksums
        run: |
          Get-FileHash td/tdlib/bin/libcrypto-3-x64.dll -Algorithm SHA256
          Get-FileHash td/tdlib/bin/libssl-3-x64.dll -Algorithm SHA256
          Get-FileHash td/tdlib/bin/tdjni.dll -Algorithm SHA256
          Get-FileHash td/tdlib/bin/zlib1.dll -Algorithm SHA256

      - name: Copy libs
        run: |
          Remove-Item -Recurse tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-x64
          New-Item -ItemType Directory -Path tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-x64
          Copy-Item td/tdlib/bin/libcrypto-3-x64.dll -Destination tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-x64/libcrypto-3-x64.dll
          Copy-Item td/tdlib/bin/libssl-3-x64.dll -Destination tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-x64/libssl-3-x64.dll
          Copy-Item td/tdlib/bin/tdjni.dll -Destination tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-x64/tdjni.dll
          Copy-Item td/tdlib/bin/zlib1.dll -Destination tdl-coroutines/src/jvmMainGenerated/resources/libs/windows-x64/zlib1.dll

      - name: Commit and push libs
        uses: EndBug/add-and-commit@v9
        with:
          pull: --rebase --autostash
          author_name: Georgii Ippolitov
          author_email: detmmpmznb@g000sha256.dev
          committer_name: GitHub
          committer_email: noreply@github.com
          message: TDLib for JVM Windows x64 [skip ci]
          add: tdl-coroutines

  check:
    needs:
      - build-android
      - build-jvm-linux-arm64
      - build-jvm-linux-x64
      - build-jvm-macos-arm64
      - build-jvm-macos-x64
      - build-jvm-windows-arm64
      - build-jvm-windows-x64
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          lfs: true
          submodules: false

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.1
          cache-disabled: false

      - name: Assemble libraries
        run: |
          ./gradlew tdl-coroutines:assembleRelease
          ./gradlew tdl-coroutines:jvmJar

      - name: Assemble examples
        run: |
          ./gradlew tdl-coroutines-example:assembleRelease
          ./gradlew tdl-coroutines-example-jvm:assemble
